---

- name: download mariadb
  get_url:
    url:  https://downloads.mariadb.org/f/mariadb-10.1.22/source/mariadb-10.1.22.tar.gz?serve
    dest: /tmp/mariadb.tar.gz

- name: uncompress mariadb
  unarchive:
    src: /tmp/mariadb.tar.gz
    dest: /tmp
    copy: no

- name: set source repo
  apt_repository:
    repo: "deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates universe"
    state: present

- name: install packages need to build mariadb
  apt:
    name: "{{item}}"
    state: build-dep
    update_cache: yes
    install_recommends: no
  with_items:
    - mariadb-server

- name: configure the mariadb build
  shell: cmake . -DBUILD_CONFIG=mysql_release
  args:
    chdir: /tmp/mariadb-10.1.22

- name: compile mariadb
  shell: (time -p make) > /tmp/compiler.log 2>&1
  args:
    executable: /bin/bash
    chdir: /tmp/mariadb-10.1.22

- name: retrieve log
  fetch:
    src: /tmp/compiler.log
    dest: ../logs/{{inventory_hostname}}/compiler.log
    flat: yes

- name: remove mariadb files
  file:
    path: /tmp/test
    state: absent
  with_items:
    - /tmp/mariadb-10.1.22
    - /tmp/mariadb.tar.gz

- name: remove installed packages
  apt:
    name: "{{item}}"
    autoremove: yes
    purge: yes
    state: absent
  with_items:
    - autotools-dev
    - binutils
    - bison
    - build-essential
    - chrpath
    - cmake
    - cmake-data
    - cpp
    - cpp-5
    - debhelper
    - dh-apparmor
    - dh-strip-nondeterminism
    - dpkg-dev
    - g++
    - g++-5
    - gcc
    - gcc-5
    - gdb
    - gettext
    - icu-devtools
    - intltool-debian
    - libaio-dev
    - libaio1
    - libarchive-zip-perl
    - libarchive13
    - libasan2
    - libatomic1
    - libbabeltrace-ctf1
    - libbabeltrace1
    - libbison-dev
    - libboost-dev
    - libboost1.58-dev
    - libc-dev-bin
    - libc6-dev
    - libcc1-0
    - libcilkrts5
    - libcroco3
    - libcurl3
    - libdpkg-perl
    - libfile-stripnondeterminism-perl
    - libgcc-5-dev
    - libgomp1
    - libicu-dev
    - libisl15
    - libitm1
    - libjemalloc-dev
    - libjemalloc1
    - libjsoncpp1
    - libjudy-dev
    - libjudydebian1
    - liblsan0
    - libltdl-dev
    - libltdl7
    - libmpc3
    - libmpx0
    - libncurses5-dev
    - libodbc1
    - libpam0g-dev
    - libpcre16-3
    - libpcre3-dev
    - libpcre32-3
    - libpcrecpp0v5
    - libquadmath0
    - libreadline-gplv2-dev
    - libstdc++-5-dev
    - libtimedate-perl
    - libtinfo-dev
    - libtsan0
    - libubsan0
    - libunistring0
    - libxml2-dev
    - linux-libc-dev
    - m4
    - make
    - odbcinst
    - odbcinst1debian2
    - po-debconf
    - unixodbc
    - unixodbc-dev
    - zlib1g-dev 
